### ISSUE TITLE
Integrate with official Unity

### ISSUE THREAD

**Issue by ENikS** [Chavoshi/Unity.NetCore#2]
Why don’t you fix official Interception package?

**Comment by Chavoshi** [comment]
Hi @ENikS.
Sure, I'll start to do it ASAP. I'll contact you once it'll be done.

**Comment by Chavoshi** [comment]
Hey @ENikS,
Unity.Configuration, Unity.Interception, and Unity.Interception.Configuration is gonna to be ready to push, please be in contact with me to decide how are we gonna to categorize it. Are we going to create new repository for them?
My suggestion is having two, one for configuration and one for interception (including Interception & Interception.Configuration).

**Comment by ENikS** [comment]
It would be ideal if you could just send a Pull request on each of these repositories. 
Once merged I'll deploy it to nuget as usual.

**Comment by ghd258** [comment]
Has the work begun yet? When will it be finished?

**Comment by Chavoshi** [comment]
I'm doing the final testings.

**Comment by ghd258** [comment]
It's hard to expect.

**Comment by Chavoshi** [comment]
@ghd258
Honestly I didn’t get you.
What do you mean by ‘It’s hard to expect’?

**Comment by ghd258** [comment]
You've been working hard
