### ISSUE TITLE
Getting Errors trying to add Interception

### ISSUE THREAD

**Issue by scovel** [Chavoshi/Unity.NetCore#3]
I have a project using .Net Standard 2.0.  Good to see Unity working in Core!  My project needs Interception for cross-cutting concerns (performance monitoring, etc) so I added Interception.  I'm getting the following error:

Error	CS0029	Cannot implicitly convert type 'Microsoft.Practices.Unity.InterceptionExtension.Interceptor<Microsoft.Practices.Unity.InterceptionExtension.InterfaceInterceptor>' to 'Unity.Registration.InjectionMember'

Isn't this library for Unity Interception?  Why doesn't it work with Unity??

**Comment by Chavoshi** [comment]
Please refer to this thread:

https://github.com/Chavoshi/Unity.NetCore/issues/2
